pipeline_id: "etl_synth_v1"
config_version: "1.1.0"

dry_run: false # если true, операции записи в БД/файлы не выполняются, только логирование

log_config:
  log_path: "logs/"
  log_level: "INFO"
  log_format: "%(asctime)s - [%(levelname)s] [%(dry_run)s] - %(name)s - %(message)s"
  log_to_console: true
  sanitize_sensitive_data: true

  sensitive_fields:
    email: partial
    phone: partial
    password: full
    token: full

  log_rotation:
    enabled: true
    when: "midnight"
    interval: 1
    backup_count: 7

  variables:
    date: "%Y-%m-%d"
    # hash можно генерировать программно на основе параметров пайплайна

  stages:
    generation:
      enabled: true
      log_dir: "logs/stages/generation/"
      log_file: "{date}_{pipeline_id}_{hash}_generation.log"
    extraction:
      enabled: true
      log_dir: "logs/stages/extraction/"
      log_file: "{date}_{pipeline_id}_{hash}_extraction.log"
    transformation:
      enabled: true
      log_dir: "logs/stages/transformation/"
      log_file: "{date}_{pipeline_id}_{hash}_transformation.log"
    validation:
      enabled: true
      log_dir: "logs/stages/validation/"
      log_file: "{date}_{pipeline_id}_{hash}_validation.log"
    profiling:
      enabled: true
      log_dir: "logs/stages/profiling/"
      log_file: "{date}_{pipeline_id}_{hash}_profiling.log"
    loading:
      enabled: true
      log_dir: "logs/stages/loading/"
      log_file: "{date}_{pipeline_id}_{hash}_loading.log"
    analytics:
      enabled: true
      log_dir: "logs/stages/analytics/"
      log_file: "{date}_{pipeline_id}_{hash}_analytics.log"

config_validation:

  required_fields:
    - pipeline_id
    - config_version
    - dry_run
    - log_config
    - generation_config
    - extraction_config
    - transformation_config
    - validation_config
    - profiling_config
    - loading_config
    - analytics_config

  types:
    pipeline_id: str
    config_version: str
    dry_run: bool

    log_config: dict
    generation_config: dict
    extraction_config: dict
    transformation_config: dict
    validation_config: dict
    profiling_config: dict
    loading_config: dict
    analytics_config: dict

  # --- log_config ---
  log_config:
    required_fields:
      - log_path
      - log_level
      - log_format
      - log_to_console
      - sanitize_sensitive_data
      - sensitive_fields
      - log_rotation
      - variables
      - stages

    types:
      log_path: str
      log_level: str
      log_format: str
      log_to_console: bool
      sanitize_sensitive_data: bool
      sensitive_fields: dict
      log_rotation: dict
      variables: dict
      stages: dict

    choices:
      log_level: ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]

    sensitive_fields:
      keys_type: str
      values_type: str
      allowed_values: ["none", "partial", "full"]

    log_rotation:
      required_fields:
        - enabled
        - when
        - interval
        - backup_count
      types:
        enabled: bool
        when: str
        interval: int
        backup_count: int

    variables:
      keys_type: str
      values_type: str

    stages:
      keys_type: str
      values_type: dict
      required_fields:
        - enabled
        - log_dir
        - log_file
      types:
        enabled: bool
        log_dir: str
        log_file: str

  # --- generation_config ---
  generation_config:
    required_fields:
      - sqlite
      - csv
      - mongo_config
      - anomaly_config

    sqlite:
      required_fields:
        - enabled
        - db_name
        - db_path
        - tables
        - word_lists
      types:
        enabled: bool
        db_name: str
        db_path: str
        tables: list
        word_lists: dict

      tables:
        list_of_dicts: true
        required_keys:
          - name
          - rows
          - columns
        columns:
          list_of_dicts: true
          required_keys:
            - name
            - type
          optional_keys:
            - options
          types:
            name: str
            type: str
            options: str

        constraints:
          list_of_str: true

      word_lists:
        keys_type: str
        values_type: list
        list_values_type: str

    csv:
      required_fields:
        - enabled
        - output
        - rows
        - schema
      types:
        enabled: bool
        output: dict
        rows: int
        schema: dict

      output:
        required_fields:
          - path
          - filename
          - delimiter
          - quotechar
          - encoding
        types:
          path: str
          filename: str
          delimiter: str
          quotechar: str
          encoding: str

      schema:
        required_fields:
          - headers
        headers:
          list_of_dicts: true
          required_keys:
            - name
            - type
          types:
            name: str
            type: str

    mongo_config:
      required_fields:
        - uri
        - db_name
        - collections
      types:
        uri: str
        db_name: str
        collections: list

      collections:
        list_of_dicts: true
        required_keys:
          - name
          - num_docs
          - schema
        types:
          name: str
          num_docs: int
          schema: dict

    anomaly_config:
      required_fields:
        - probability
        - strategies
      types:
        probability: float
        strategies: dict

      strategies:
        keys_type: str
        values_type: list

  # --- extraction_config ---
  extraction_config:
    required_fields:
      - api
      - csv_sources
      - sqlite_sources

    api:
      keys_type: str
      values_type: dict
      dict_fields:
        required_fields:
          - url
          - method
          - params
          - headers
          - format
          - enabled
        types:
          url: str
          method: str
          params: dict
          headers: dict
          format: str
          enabled: bool

    csv_sources:
      list_of_dicts: true
      required_keys:
        - name
        - path
        - delimiter
        - encoding
        - header
        - enabled
      types:
        name: str
        path: str
        delimiter: str
        encoding: str
        header: bool
        enabled: bool

    sqlite_sources:
      list_of_dicts: true
      required_keys:
        - name
        - path
        - tables
        - enabled
      types:
        name: str
        path: str
        tables: list
        enabled: bool

  # --- transformation_config ---
  transformation_config:
    required_fields:
      - enabled
      - operations
      - operation_order
    types:
      enabled: bool
      operations: dict
      operation_order: list

    operations:
      keys_type: str
      values_type: dict
      dict_fields:
        required_fields:
          - enabled
        types:
          enabled: bool

    operation_order:
      list_of_str: true

  # --- validation_config ---
  validation_config:
    required_fields:
      - enabled
      - foreign_keys
      - composite_keys
      - constraints
    types:
      enabled: bool
      foreign_keys: dict
      composite_keys: dict
      constraints: dict

    foreign_keys:
      keys_type: str
      values_type: dict
      inner_keys_type: str
      inner_values_type: str

    composite_keys:
      keys_type: str
      values_type: list
      list_values_type: list

    constraints:
      keys_type: str
      values_type: list
      list_values_type: str

  # --- profiling_config ---
  profiling_config:
    required_fields:
      - enabled
      - reports_path
      - format
      - detailed
      - group_by
      - include_columns
      - exclude_columns
      - stats
    types:
      enabled: bool
      reports_path: str
      format: list
      detailed: bool
      group_by: list
      include_columns: list
      exclude_columns: list
      stats: list

  # --- loading_config ---
  loading_config:
    required_fields:
      - sqlite
      - clickhouse
      - postgres
    types:
      sqlite: dict
      clickhouse: dict
      postgres: dict

    sqlite:
      required_fields:
        - enabled
        - db_name
        - db_path
        - if_exists
        - timeout
        - log
      types:
        enabled: bool
        db_name: str
        db_path: str
        if_exists: str
        timeout: int
        log: bool

    clickhouse:
      required_fields:
        - enabled
        - host
        - port
        - user
        - password
        - secure
        - compression
        - database
        - table_mappings
      types:
        enabled: bool
        host: str
        port: int
        user: str
        password: str
        secure: bool
        compression: bool
        database: str
        table_mappings: dict

    postgres:
      required_fields:
        - enabled
        - host
        - port
        - user
        - password
        - database
        - schema
        - sslmode
        - batch_size
        - table_mappings
      types:
        enabled: bool
        host: str
        port: int
        user: str
        password: str
        database: str
        schema: str
        sslmode: str
        batch_size: int
        table_mappings: dict

  # --- analytics_config ---
  analytics_config:
    required_fields:
      - predefined_queries
    types:
      predefined_queries: dict

    predefined_queries:
      keys_type: str
      values_type: dict

      # Внутренние запросы на уровне 2: ключ: SQL строка
      dict_values:
        keys_type: str
        values_type: str
