log_config:
  log_path: "logs/"
  log_level: "INFO"   # уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_rotation:
    enabled: true
    when: "midnight"
    interval: 1
    backup_count: 7

  stages:
    extraction:
      enabled: true
      log_file: "{date}_extraction.log"
    transformation:
      enabled: true
      log_file: "{date}_transformation.log"
    validation:
      enabled: true
      log_file: "{date}_validation.log"
    profiling:
      enabled: true
      log_file: "{date}_profiling.log"
    loading:
      enabled: true
      log_file: "{date}_loading.log"
