log_path: "logs/"
log_level: "INFO"
log_format:
  pattern: "%(asctime)s - [%(levelname)s] [%(dry_run)s] - %(name)s - %(message)s"
  format: json
log_to_console: true
color_log: true
sanitize_sensitive_data: true

sensitive_fields:
  email: partial
  phone: partial
  password: full
  token: full
  api_key: partial
  auth_key: partial

log_rotation:
  enabled: true
  when: "midnight"
  interval: 1
  backup_count: 7

variables:
  date: "%Y-%m-%d"
  # hash можно генерировать программно на основе параметров пайплайна

stages:
  generation:
    enabled: true
    log_dir: "logs/stages/generation/"
    log_file: "{date}_{pipeline_id}_{hash}_generation.log"
  extraction:
    enabled: true
    log_dir: "logs/stages/extraction/"
    log_file: "{date}_{pipeline_id}_{hash}_extraction.log"
  transformation:
    enabled: true
    log_dir: "logs/stages/transformation/"
    log_file: "{date}_{pipeline_id}_{hash}_transformation.log"
  validation:
    enabled: true
    log_dir: "logs/stages/validation/"
    log_file: "{date}_{pipeline_id}_{hash}_validation.log"
  profiling:
    enabled: true
    log_dir: "logs/stages/profiling/"
    log_file: "{date}_{pipeline_id}_{hash}_profiling.log"
  loading:
    enabled: true
    log_dir: "logs/stages/loading/"
    log_file: "{date}_{pipeline_id}_{hash}_loading.log"
  analytics:
    enabled: true
    log_dir: "logs/stages/analytics/"
    log_file: "{date}_{pipeline_id}_{hash}_analytics.log"
