profiling:
  enabled: true
  reports_path: "./reports/profiling/"
  detailed: false
  include_columns: []  # если не пустой, применится фильтрация по колонкам
  exclude_columns: []

  stats:
    - count
    - mean
    - median
    - std
    - min
    - max
    - missing_values
    - unique
    - mode
    - null_percentage
    - histogram
