data_sources:
  api:
    fakestore:
      url: "https://fakestoreapi.com/products"
      method: "GET"
      params: {}
      headers:
        Accept: "application/json"
      format: json
      enabled: true

  csv_sources:
    - name: employees
      path: "data/employees_synth_data.csv"
      delimiter: ","
      encoding: "utf-8"
      header: true
      enabled: true

  sqlite_sources:
    - name: synthetic_db
      path: "data/synth_sqlite_database.db"
      tables:
        - users
        - products
        - logs
        - transactions
        - user_actions
        - orders
      enabled: true
