api:
  fakestore:
    url: "https://fakestoreapi.com/products"
    method: GET
    params: {}
    headers:
      Accept: "application/json"
csv:
  path: data/
  include: ["*.csv"]

sqlite:
  path: data/
  include: ["*.db"]